### ISSUE TITLE
Similar functionality in Node?

### ISSUE THREAD

**Issue by bahmutov** [Clever/aviator#39]
Hi guys,
Great job with aviator - sorry for the silly question - do you know of a similar tool implemented in Node? I would love to use all JS solution for my testing.

**Comment by mohit** [comment]
Hi @bahmutov I'm curious about the use case that would benefit from an all JS solution?

**Comment by nathanleiby** [comment]
@bahmutov thanks for your interest in the project! I unfortunately don't know of a similar tool in Node.

However, one of the great features of Go is that it's easy to compile binaries that across many OSs. You can see we have a Linux and Mac 64-bit [releases](https://github.com/Clever/aviator/releases). I imagine you could integrate these into your testing.

For example, you could add a build step that pulls the aviator binary, e.g. downloading it with wget:

```
wget https://github.com/Clever/aviator/releases/download/v0.2.2/aviator-v0.2.2-darwin-amd64.tar.gz
```

**Comment by bahmutov** [comment]
Hi, thanks for looking at this question,
The benefit from all JS solution for me would be simple integration with other JS build tools (grunt, gulp) and simple additional logic. Could not really find anything similar.

**Comment by nathanleiby** [comment]
@bahmutov Sorry, this doesn't yet seem like precisely the right tool. If you wanted to extend it to work in Node, perhaps you could wrap calls to the Aviator binary and create a JS API.

**Comment by bahmutov** [comment]
I wrote quickly - same idea, but only using local `quickly.js` configuration paths, no service registrations (uses relative or absolute paths). https://github.com/bahmutov/quickly

**Comment by nathanleiby** [comment]
@bahmutov thanks for sharing!
