### ISSUE TITLE
Trouble installing aviator following Readme

### ISSUE THREAD

**Issue by Lothiraldan** [Clever/aviator#53]
Hi, I tried to install aviator using README cli example and if fails.

~~~
go get github.com/Clever/aviator/
package github.com/Clever/aviator
	imports github.com/Clever/aviator
	imports github.com/Clever/aviator: no buildable Go source files in /Users/lothiraldan/go/src/github.com/Clever/aviator
~~~

Any idea why?

**Comment by rgarcia** [comment]
Sorry about that! We moved things around and the correct command is now `go get github.com/Clever/aviator/cmd/aviator`. I'll update the readme.
